name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # state management
  go_router: ^16.0.0 # for navigation
  cached_network_image: ^3.4.1 # for image caching
  http: ^1.4.0 # for api calls
  path: ^1.9.1 # for path
  sqflite: ^2.4.2 # for local storage
  url_launcher: ^6.3.2 # for opening url in browser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
